"""Initial Generation

Revision ID: f2fe2c5cdace
Revises: 8cafc0fb6ccc
Create Date: 2025-10-14 01:58:31.474413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2fe2c5cdace'
down_revision: Union[str, Sequence[str], None] = '8cafc0fb6ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('band', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('band', 'date')
    # ### end Alembic commands ###
